import type { User, Post, Tag, Event } from './types';

export const users: User[] = [
    {
        id: 'u1',
        name: 'Kenji Tanaka',
        email: 'kenji.tanaka@example.com',
        avatarUrl: 'https://picsum.photos/seed/user1/200/200',
        affiliation: 'University of Tokyo',
        country: 'Japan',
    },
    {
        id: 'u2',
        name: 'Priya Sharma',
        email: 'priya.sharma@example.com',
        avatarUrl: 'https://picsum.photos/seed/user2/200/200',
        affiliation: 'Indian Institute of Technology, Bombay',
        country: 'India',
    },
    {
        id: 'u3',
        name: 'Yuki Nakamura',
        email: 'yuki.nakamura@example.com',
        avatarUrl: 'https://picsum.photos/seed/user3/200/200',
        affiliation: 'Kyoto University',
        country: 'Japan',
    },
    {
        id: 'u4',
        name: 'Arjun Verma',
        email: 'arjun.verma@example.com',
        avatarUrl: 'https://picsum.photos/seed/user4/200/200',
        affiliation: 'Indian Institute of Science',
        country: 'India',
    },
];

export const tags: Tag[] = [
    { id: 't1', name: 'Robotics' },
    { id: 't2', name: 'Environmental Science' },
    { id: 't3', name: 'AI & Machine Learning' },
    { id: 't4', name: 'Linguistics' },
    { id: 't5', name: 'Cultural Studies' },
    { id: 't6', name: 'Bio-Technology' },
];

export const posts: Post[] = [
    {
        id: 'p1',
        title: 'Advancements in Collaborative Robotics',
        excerpt: 'Exploring the synergy between human and machine collaboration in modern manufacturing and healthcare.',
        imageUrl: 'https://picsum.photos/seed/post1/600/400',
        authorId: 'u1',
        tags: ['t1', 't3'],
        createdAt: '2024-05-15T10:00:00Z',
        readTime: 8,
        commentsCount: 12,
        language: 'en',
    },
    {
        id: 'p2',
        title: 'Sustainable Agriculture in West Bengal',
        excerpt: 'A case study on innovative and sustainable farming techniques being adopted by local communities.',
        imageUrl: 'https://picsum.photos/seed/post2/600/400',
        authorId: 'u2',
        tags: ['t2'],
        createdAt: '2024-05-14T14:30:00Z',
        readTime: 12,
        commentsCount: 23,
        language: 'en',
    },
    {
        id: 'p3',
        title: '都市言語学の新しいアプローチ',
        excerpt: '東京の多様な言語景観を分析し、都市空間における言語の役割を再考する。',
        imageUrl: 'https://picsum.photos/seed/post3/600/400',
        authorId: 'u3',
        tags: ['t4', 't5'],
        createdAt: '2024-05-12T09:00:00Z',
        readTime: 15,
        commentsCount: 8,
        language: 'ja',
    },
    {
        id: 'p4',
        title: 'A Primer on Federated Learning',
        excerpt: 'Understanding the fundamentals of federated machine learning and its privacy-preserving benefits.',
        imageUrl: 'https://picsum.photos/seed/post4/600/400',
        authorId: 'u4',
        tags: ['t3'],
        createdAt: '2024-05-10T18:00:00Z',
        readTime: 10,
        commentsCount: 31,
        language: 'en',
    },
     {
        id: 'p5',
        title: 'The Aesthetics of Japanese Gardens',
        excerpt: 'An in-depth look at the principles of balance, harmony, and nature in traditional Japanese garden design.',
        imageUrl: 'https://picsum.photos/seed/post5/600/400',
        authorId: 'u1',
        tags: ['t5'],
        createdAt: '2024-05-09T11:20:00Z',
        readTime: 7,
        commentsCount: 15,
        language: 'en',
    },
    {
        id: 'p6',
        title: 'インドの祭りと地域社会',
        excerpt: '多様な祭りがインドの地域社会の結束をどのように強化しているかについての考察。',
        imageUrl: 'https://picsum.photos/seed/post6/600/400',
        authorId: 'u2',
        tags: ['t5'],
        createdAt: '2024-05-08T16:45:00Z',
        readTime: 9,
        commentsCount: 18,
        language: 'ja',
    },
];

export const events: Event[] = [
    {
        id: 'e1',
        title: 'AI in Healthcare: A Joint Webinar',
        date: '2024-06-10T10:00:00Z',
        type: 'Webinar',
    },
    {
        id: 'e2',
        title: 'Cross-Cultural Communication Workshop',
        date: '2024-06-25T13:00:00Z',
        type: 'Workshop',
    },
];
